
/// Hämtar alla poster på hemsidan så de visas på STARTSIDAN
GET http://localhost:3001/api/post

###

/// Hämtar alla poster från en användare 
GET http://localhost:3001/api/admin/post

###

/// Skapar en post
POST http://localhost:3001/api/admin/post
Content-Type: application/json

{
    "title": "Nytt test",
    "content": "Testar att skapa en post"
}

###

/// Ändrar en post
PUT http://localhost:3001/api/admin/post/60acf179df9ee646d81e9c87
Content-Type: application/json

{
    "title": "Nytt edit test",
    "content": "Nu är posten ändrad"
}

###

/// Tar bort en post
DELETE http://localhost:3001/api/post/60a51024bf899b53140a215b
