
/// Hämtar alla poster på hemsidan så de visas på STARTSIDAN
GET http://localhost:3001/api/post

###

/// Hämtar alla poster från en användare 
GET http://localhost:3001/api/admin/post

###

/// Skapar en post
POST http://localhost:3001/api/admin/post
Content-Type: application/json

{
    "title": "Test",
    "content": "Testar att skapa en post"
}

###

/// Ändrar en post
PUT http://localhost:3001/api/admin/post/608a678747668c942c284c0e
Content-Type: application/json

{
   
    "title": "Test",
    "content": "Testar att ändra en post"
}

###

/// Tar bort en post
DELETE http://localhost:3001/api/post/id
