GET http://localhost:3001/api/user

###

POST http://localhost:3001/api/user/register
Content-Type: application/json

{
    "email": "fsdf@test.se",
    "password": "test12"
}

###

POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "nicklas@test.se",
    "password": "dfgasdg"
}

###

GET http://localhost:3001/api/user/logout

###

GET http://localhost:3001/api/user/auth

###

// För VG
PUT http://localhost:3001/api/user/608163124e6aad6244ba7508
Content-Type: application/json

{
    "authorKey": "1",
    "author": "CiiD",
    "title": "Rubrik",
    "salt": "Massa Lorem"
}

###

// VG
DELETE http://localhost:3001/api/user/60816d3718d9ca0818fa418e
